services:
  smart-box:
    environment:
      ENABLE_SERIAL_CONTROLLER: "true"
      ENABLE_STATION_SIGNAL: "false"
      SERIAL_PORT: "/dev/ttyACM0"
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
